apiVersion: apps/v1
kind: Deployment
metadata:
  name: forkfly-deployment
  labels:
    app: forkfly-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: forkfly-app
  template:
    metadata:
      labels:
        app: forkfly-app
    spec:
      containers:
      - name: forkfly-app-ctl
        image: samratsooraj/forkfly:latest
        ports:
        - containerPort: 8001
